from app.llm.client import llm


def research_destination(destination: str) -> dict:
    """
    Researches a destination and returns structured information.
    """

    prompt = f"""
You are a travel research agent.

Research the destination: {destination}

Provide useful information under exactly these sections:

1. Attractions
2. Activities
3. Travel Tips
4. Best Areas to Stay
5. Important Notes

Keep the information practical and concise.
Do not invent exact prices or opening hours.
"""

    response = llm.invoke(prompt)

    # Get only the text generated by Gemini
    text = response.content

    return {
        "destination": destination,
        "research": text
    }