from app.llm.client import llm
from app.graph.state import TravelState


def optimization_agent(state: TravelState) -> dict:
    """
    Reviews the generated itinerary and improves feasibility,
    budget consistency, travel time, weather suitability, and
    user preference alignment.
    """

    destination = state.get("destination", "")
    duration_days = state.get("duration_days") or 1
    travelers = state.get("travelers") or 1

    budget = state.get("budget") or 0
    currency = state.get("currency") or "UNKNOWN"

    preferences = state.get("preferences", [])
    constraints = state.get("constraints", [])

    itinerary = state.get("itinerary", [])

    destination_info = state.get("destination_info", {})
    accommodation = state.get("accommodation_options", [])
    transport = state.get("transport_options", [])
    weather = state.get("weather", {})

    estimated_cost = state.get("estimated_cost", 0)
    budget_remaining = state.get("budget_remaining", 0)
    budget_status = state.get("budget_status", "UNKNOWN")

    prompt = f"""
You are the Optimization Agent in an Agentic AI Travel Planning System.

Review and optimize the itinerary generated by the Itinerary Agent.

==================================================
TRIP
==================================================

Destination:
{destination}

Duration:
{duration_days} days

Travelers:
{travelers}

Budget:
{budget} {currency}

Preferences:
{preferences}

Constraints:
{constraints}

==================================================
CURRENT ITINERARY
==================================================

{itinerary}

==================================================
DESTINATION INFORMATION
==================================================

{destination_info}

==================================================
ACCOMMODATION
==================================================

{accommodation}

==================================================
TRANSPORT
==================================================

{transport}

==================================================
WEATHER
==================================================

{weather}

==================================================
BUDGET
==================================================

Estimated Cost:
{estimated_cost} {currency}

Budget Remaining:
{budget_remaining} {currency}

Budget Status:
{budget_status}

==================================================
OPTIMIZATION RULES
==================================================

1. Keep the destination EXACTLY as:
{destination}

2. Never replace the destination.

3. Never assume Dubai.

4. Never assume Tokyo.

5. Keep EXACTLY {duration_days} days.

6. Keep the Morning / Afternoon / Evening structure.

7. Remove unrealistic activities.

8. Avoid excessive activities in one day.

9. Group geographically nearby attractions where possible.

10. Reduce unnecessary travel.

11. Consider transportation availability.

12. Consider weather suitability.

13. Respect the user's preferences.

14. Respect the user's constraints.

15. Keep the itinerary consistent with the budget.

16. Do not claim live prices.

17. Do not claim live opening hours.

18. Do not claim live availability.

19. Use approximate information only.

20. Preserve useful activities from the original itinerary unless
    there is a clear reason to change them.

==================================================
OUTPUT
==================================================

Return:

OPTIMIZATION_STATUS:
OPTIMIZED

OPTIMIZATION_NOTES:
Briefly explain what was improved.

OPTIMIZED_ITINERARY:

Then provide the complete optimized itinerary.

Use:

DAY 1
Morning:
Activity:
Location:
Estimated Cost:
Notes:

Afternoon:
Activity:
Location:
Estimated Cost:
Notes:

Evening:
Activity:
Location:
Estimated Cost:
Notes:

Day Summary:

Repeat through DAY {duration_days}.

FINAL WARNINGS:
List important approximate or planning limitations.
"""

    print("\n===== OPTIMIZATION AGENT =====")
    print("Checking and optimizing itinerary...")

    response = llm.invoke(prompt)

    optimized_text = response.content.strip()

    print("Itinerary optimization completed.")

    return {
        "optimized_itinerary": optimized_text,
        "optimization_status": "OPTIMIZED",
    }